function htmlTagRevision(a,b,c){if(0<DEXTTOP.G_CURREDITOR._config.htmlCorrectionLimitLength&&a.length>DEXTTOP.G_CURREDITOR._config.htmlCorrectionLimitLength)return a;var d=a;if(""!=d&&(DEXTTOP.DEXT5.browser.ie&&11>=DEXTTOP.DEXT5.browser.ieVersion||DEXTTOP.DEXT5.browser.gecko))try{var e=d.toLowerCase().indexOf("<body"),f=d.toLowerCase().lastIndexOf("<body");if(-1<e&&-1<f&&e!=f)return a;if("ieplugin"!=DEXTTOP.G_CURREDITOR._config.runtimes&&-1<d.indexOf("mso-fareast-font-family")){var g=RegExp("<[^>]+style=(.*?)>",
"gi"),h="",e=!1;try{var l=d.match(g);if(l){for(var k=l.length,g=0;g<k;g++)d=d.replace(l[g],"_DEXT_T_S{"+g+"}_");for(g=0;g<k;g++){var m=l[g];-1<m.indexOf("-font-family")&&(m=m.replace("-font-family","-font-dext-family"));f=!1;0>m.indexOf("font-family")&&(f=!0);-1<m.indexOf("-font-dext-family")&&(m=m.replace("-font-dext-family","-font-family"));f&&(m=m.replace(/mso-fareast-font-family/gi,"font-family"));d=d.replace("_DEXT_T_S{"+g+"}_",m)}}}catch(t){e=!0}e&&(d=a)}b&&(d=DEXT5_EDITOR.HTMLParser.RemoveOfficeTag(d,
c));var h=d.toLowerCase(),p=realValue2=d,n=h.lastIndexOf("<body"),q=h.indexOf("</body");if(-1<n&&-1<q)try{var r=p.substring(q),u=p.substring(n).indexOf(">"),v=p.substring(0,n+u+1),d=p.substring(n+u+1,q)}catch(w){n=q=-1,d=realValue2}realValue2=null;d=DEXT5_EDITOR.HTMLParser.HTMLtoXML(d,c);-1<n&&-1<q&&(d=v+d+r)}catch(x){return a}else{if("1"==DEXTTOP.G_CURREDITOR._config.removeComment)for(b=d.indexOf("\x3c!--"),a=d.indexOf("--\x3e");-1<b&&-1<a;)b=d.substring(0,b),d=d.substring(a+3),d=b+d,b=d.indexOf("\x3c!--"),
a=d.indexOf("--\x3e");else d=d.replace(/--\x3e\s</gi,"--\x3e<");if("1"==DEXTTOP.G_CURREDITOR._config.removeCarriageReturnInTag)try{for(g=RegExp("(<[^>]*?)\n([^]*?>)","gi");g.test(d);)d=d.replace(g,"$1 $2")}catch(y){}}return d}var G_wordProcessorType="";
function SetCorrectOfficeHtml(a){var b=a;if(-1<a.indexOf("<meta name=ProgId content=Word.Document>")||-1<a.indexOf('<meta name=Generator content="Microsoft Word'))G_wordProcessorType="DOC",a=GetMsWordHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=Excel.Sheet>"))G_wordProcessorType="XLS",a=GetMsExcelHtml(a);else if(-1<a.indexOf("<meta name=ProgId content=PowerPoint.Slide>")){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==DEXTTOP.G_CURREDITOR._config.removeTdStyleInPastePpt){for(var c=
RegExp("<(td|th)([^>]*?)style='([^']*?)(font-size:18.0pt;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-size:18.0pt;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">');for(c=RegExp("<(td|th)([^>]*?)style='([^']*?)(font-family:Arial;)([^']*?)'>","gi");c.test(a);)a=a.replace(c,"<$1$2style='$3$5'>");for(c=RegExp('<(td|th)([^>]*?)style="([^"]*?)(font-family:Arial;)([^"]*?)">',"gi");c.test(a);)a=a.replace(c,'<$1$2style="$3$5">')}}else if(-1<
a.indexOf('<meta name=Generator content="Jungum Global">'))G_wordProcessorType="GUL",a=GetJungumHtml(a);else if(isHwpPasteAction(a))G_wordProcessorType="HWP",a=GetHanHwpHtml(a);else if(-1<a.indexOf(' xmlns:m="http://schemas.microsoft.com/office/')){if(G_wordProcessorType="PPT",a=GetMsPptHtml2(a),"1"==DEXTTOP.G_CURREDITOR._config.removeTdStyleInPastePpt){for(c=RegExp("<(td|th)([^>]*?)style=('|\")([^']*?)(font-size:18.0pt;)([^']*?)('|\")>","gi");c.test(a);)a=a.replace(c,"<$1$2style=$3$4$6$7>");for(c=
RegExp("<(td|th)([^>]*?)style=('|\")([^']*?)(font-family:Arial;)([^']*?)('|\")>","gi");c.test(a);)a=a.replace(c,"<$1$2style=$3$4$6$7>")}}else-1<a.indexOf('<meta name=Generator content="Microsoft')?(G_wordProcessorType="DOC",a=GetMsWordHtml(a)):DEXTTOP.DEXT5.browser.ie||(b=a.indexOf("\x3c!--StartFragment--\x3e"),c=a.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<b&&-1<c&&(b=a.substr(b+20),c=b.lastIndexOf("\x3c!--EndFragment--\x3e"),-1<c&&(a=b=b.substring(0,c))));a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportEmptyParas]>",
"");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[if !supportEmptyParas]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[if !supportLists]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--[endif]--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if ppt]>","")}
function GetMsWordHtml(a){var b=a,c,b=a.indexOf("/* Style Definitions */"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+23),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));var b=a,d=!1,e="\x3c!--StartFragment--\x3e",f="\x3c!--EndFragment--\x3e",g=a.indexOf(e),h=a.indexOf(f);if(-1==g&&-1==h){var e="<body ",f="</body>",l=a.indexOf(e);-1<l&&(h=a.indexOf(">",l),e=a.Mid(l,h-l+1),g=a.indexOf(e),h=a.indexOf(f))}if(-1<g&&-1<h&&(b=a.substr(g+e.length),h=b.indexOf(f),-1<h)){for(;;)if(a=
b.indexOf(f,h+f.length),-1<a)h=a;else break;a=b=b.substring(0,h);d=!0}if(d){a=b;var k="<div class=WordSection1>",f=a.indexOf(k);-1==f&&(k='<div class="WordSection1">',f=a.indexOf(k));-1<f&&(k=DEXTTOP.DEXT5.util.replaceAll(a,k,""),k.length!=a.length&&(a=k,k=a.lastIndexOf("/"),-1<k&&(a=a.substring(0,k-1))));e="\x3c!--[if supportFields]>";for(f="<![endif]--\x3e";;){g=a.indexOf(e);-1<g&&(h=a.indexOf(f,g+e.length));k=a.length;if(g>k||h>k)break;if(-1<g&&-1<h){if(g<h){var m,b=a.substring(0,g);m=a.substr(h+
f.length);a=b+m}}else break;h=-1}}if(d){e="\x3c!--[if gte vml 1]>";f="<![if !vml]>";try{for(;;){g=a.indexOf(e);-1<g&&(h=a.indexOf(f,g+e.length));var t=a.length;if(t>g||t>h){a=DEXTTOP.DEXT5.util.replaceAll(a,e,"");a=DEXTTOP.DEXT5.util.replaceAll(a,f,"");break}if(-1<g&&-1<h)g>h?(b=a.substring(0,g),m=a.substr(g),b=DEXTTOP.DEXT5.util.replaceAll(b,f,""),a=b+m):(b=a.substring(0,g),m=a.substr(h+f.length),a=b+m,d=!0);else break}}catch(p){}}e="\x3c!--[if gte mso 9]>";f="<![endif]--\x3e";try{for(;;){g=a.indexOf(e);
-1<g&&(h=a.indexOf(f,g+e.length));k=a.length;if(g>k||h>k){a=DEXTTOP.DEXT5.util.replaceAll(a,e,"");a=DEXTTOP.DEXT5.util.replaceAll(a,f,"");break}if(-1<g&&-1<h)g>h?(b=a.substring(0,g),m=a.substr(g),b=DEXTTOP.DEXT5.util.replaceAll(b,f,"")):(b=a.substring(0,g),m=a.substr(h+f.length)),a=b+m;else break}}catch(n){}d&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"><![endif]></span>"," /></span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]></span>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>",
"</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !vml]>",""));a=RepaireSpanInImageTag4MsWord(a);if(0<DEXTTOP.G_CURREDITOR._config.clipImageHex.length){try{var q=RegExp("<img[^>]+file://[^>]+>","gi"),r=a.match(q);if(r){var u=r.length;if(u==DEXTTOP.G_CURREDITOR._config.clipImageHex.length)for(m=0;m<u;m++){var v=DEXTTOP.DEXT5.util.hexToBytes(DEXTTOP.G_CURREDITOR._config.clipImageHex[m].hex),v=DEXTTOP.DEXT5.util.bytesToBase64(v),q=/<img[^>]*src=["']?([^>"']+)["']?[^>]*>/;
if(q.test(r[m])){var w=r[m].replace(RegExp.$1,"data:"+DEXTTOP.G_CURREDITOR._config.clipImageHex[m].type+";base64,"+v);a=a.replace(r[m],w)}}}}catch(x){}DEXTTOP.G_CURREDITOR._config.clipImageHex=[]}a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:rect ","<div ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:rect>","</div>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shadow ","<hr ");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shape ","<span ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:shape>","</span>");a=DEXTTOP.DEXT5.util.replaceAll(a,
"<v:imagedata","<img border=0");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportLists]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");return a=setPasteClassStyle(c,a,!0)}
function GetMsExcelHtml(a){var b=a,c,b=a.indexOf("<style>"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+7),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));var b=a,d=!1,e,f="</body>",g=a.indexOf("<table"),h=a.indexOf(f);-1<g&&-1<h&&(b=a.substr(g),h=b.indexOf(f),-1<h&&(b=b.substring(0,h),d=!0));if(d){d=!1;a=b;e="\x3c!--[if gte vml 1]>";f="<![if !vml]>";try{for(;;){g=a.indexOf(e);-1<g&&(h=a.indexOf(f,g+e.length));var l=a.length;if(l>g||l>h){a=DEXTTOP.DEXT5.util.replaceAll(a,
e,"");a=DEXTTOP.DEXT5.util.replaceAll(a,f,"");break}if(-1<g&&-1<h)if(g>h){var k,b=a.substring(0,g);k=a.substr(g);b=DEXTTOP.DEXT5.util.replaceAll(b,f,"");a=b+k}else b=a.substring(0,g),k=a.substr(h+f.length),a=b+k,d=!0;else break}}catch(m){}}d&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"></span><![endif]>"," /></span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),l=_T("<![if !vml]>"),a=DEXTTOP.DEXT5.util.replaceAll(a,l,""));a=DEXTTOP.DEXT5.util.replaceAll(a,
"<v:rect ","<div ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:rect>","</div>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shadow ","<hr ");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:shape ","<span ");a=DEXTTOP.DEXT5.util.replaceAll(a,"</v:shape>","</span>");a=DEXTTOP.DEXT5.util.replaceAll(a,"<v:imagedata","<img border=0");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--StartFragment--\x3e","");a=DEXTTOP.DEXT5.util.replaceAll(a,"\x3c!--EndFragment--\x3e","");l=a.indexOf("<col ");-1<l&&(a=a.substring(0,l)+"\n<colgroup>\n"+
a.substring(l,a.length+1));l=a.indexOf("<tr ");-1<l&&(a=a.substring(0,l)+"\n<tbody>\n"+a.substring(l,a.length+1),l=a.lastIndexOf("</table>"),-1<l&&(a=a.substring(0,l)+"\n</tbody>\n"+a.substring(l,a.length+1)));a=setPasteClassStyle(c,a);"1"==DEXTTOP.G_CURREDITOR._config.officeLineFix&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"border-left:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-top:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-right:none;",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"border-bottom:none;",
""));a=DEXTTOP.DEXT5.util.replaceAll(a,"\r","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"\n","")}
function GetMsPptHtml2(a){var b=a,c,b=a.indexOf("\x3c!--tr"),d=a.indexOf("</head>");-1<b&&-1<d&&(b=a.substr(b+6),d=b.indexOf("</head>"),-1<d&&(c=b.substring(0,d),c=GetStyleMap(c)));b=a.indexOf("\x3c!--StartFragment--\x3e");d=a.indexOf("\x3c!--EndFragment--\x3e");if(-1<b&&-1<d&&(b=a.substr(b+20),d=b.indexOf("\x3c!--EndFragment--\x3e"),-1<d)){for(;;)if(a=b.indexOf("\x3c!--EndFragment--\x3e",d+18),-1<a)d=a;else break;a=b=b.substring(0,d)}a=setPasteClassStyle(c,a);"1"==DEXTTOP.G_CURREDITOR._config.officeLineFix&&
(a=DEXTTOP.DEXT5.util.replaceAll(a,"border-right:none;",""));c=RegExp("<spanstyle","ig");a=a.replace(c,"<span style");return a=a.replace(c,"<p style")}
function GetJungumHtml(a){if("1"==DEXTTOP.G_CURREDITOR._config.useHtmlProcessByWorker)return a;var b=a.indexOf("<body>"),c=a.indexOf("</body>"),d=!1;-1<b&&-1<c&&(strTemp=a.substr(b+6),c=strTemp.indexOf("</body>"),-1<c&&(a=strTemp=strTemp.substring(0,c),d=!0));if(d){b=document.createElement("div");b.innerHTML=a;a=b.getElementsByTagName("table");for(var c=a.length,e,f,d=0;d<c;d++)""!=a[d].getAttribute("width")&&(e=parseInt(a[d].getAttribute("width"),10)),""!=a[d].getAttribute("height")&&(f=parseInt(a[d].getAttribute("height"),
10)),e&&(a[d].style.width=e+"px"),f&&(a[d].style.height=f+"px");a=b.innerHTML}return a}
function GetHanHwpHtml(a){var b=a,b=">\x3c!--p.0",c="</head>",d,e=a.indexOf(b),f=a.indexOf(c);-1==e&&(b=">\r\n\x3c!--p.0",e=a.indexOf(b));-1==e&&(b="\x3c!--p.0",e=a.indexOf(b));-1==f&&(c="</HEAD>",f=a.indexOf(c));-1<e&&-1<f&&(b=a.substr(e+(b.length-3)),f=b.indexOf(c),-1<f&&(d=b.substring(0,f),d=GetStyleMap(d)));var b=a,g=!1,h="\x3c!--StartFragment--\x3e",c="\x3c!--EndFragment--\x3e",f=a.indexOf(h),e=a.indexOf(c);if(-1<f&&-1<e&&(b=a.substr(f+h.length),e=b.indexOf(c),-1<e)){for(;;)if(g=b.indexOf(c,
e+c.length),-1<g)e=g;else break;b=b.substring(0,e);g=!0}if(g){g=!1;a=b;h="\x3c!--[if gte vml 1]>";c="<![if !vml]>";try{for(;;){f=a.indexOf(h);-1<f&&(e=a.indexOf(c,f+h.length));var l=a.length;if(l>f||l>e){a=DEXTTOP.DEXT5.util.replaceAll(a,h,"");a=DEXTTOP.DEXT5.util.replaceAll(a,c,"");break}if(-1<f&&-1<e)if(f>e){var k,b=a.substring(0,f);k=a.substr(f);b=DEXTTOP.DEXT5.util.replaceAll(b,c,"");a=b+k}else b=a.substring(0,f),k=a.substr(e+c.length),a=b+k,g=!0;else break}}catch(m){}}a=setPasteClassStyle(d,
a);g&&(a=DEXTTOP.DEXT5.util.replaceAll(a,"/><![endif]>"," />"),a=DEXTTOP.DEXT5.util.replaceAll(a,"</span><![endif]>","</span>"),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>",""),a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !vml]>",""));a=DEXTTOP.DEXT5.util.replaceAll(a,"<![if !supportEmptyParas]>&nbsp;<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"<![endif]>","");a=DEXTTOP.DEXT5.util.replaceAll(a,"background:#ffffff;","");a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-fareast-","");a=DEXTTOP.DEXT5.util.replaceAll(a,
"mso-hansi-","");a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-ascii-","");a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-bidi-","");return a=DEXTTOP.DEXT5.util.replaceAll(a,"mso-","")}
function GetStyleMap(a){var b={};a=a.split("}");for(var c="",d=a.length,e=0;e<d;e++){var f=a[e].split("{"),g=f.length;if(2==g)for(var h=0;h<g-1;h++){var l=f[h],k=f[h+1],l=l.replace(/\r\n/g,""),l=l.replace(/\r/g,""),l=l.replace(/\n/g,""),l=l.replace(/\t/g,""),k=k.replace(/\r\n/g,""),k=k.replace(/\r/g,""),k=k.replace(/\n/g,""),k=k.replace(/\t/g,"");""==c&&"td"==l&&(c=k=DEXTTOP.DEXT5.util.replaceAll(k,"'",'"'));0<l.length&&(k=DEXTTOP.DEXT5.util.replaceAll(k,"'",'"'),"."==l.substring(0,1)&&0<c.length?
(k=k.replace(/font-family:&quot,/g,"font-family:"),b[l]=c+k):b[l]=k)}}return b}
function RepaireSpanInImageTag4MsWord(a){for(var b,c,d,e,f;;)if(b="<v:shape ",c=a.indexOf(b),-1==c&&(b="<v:shape\r\n",c=a.indexOf(b)),-1<c)if(d=a.indexOf("</v:shape>",c+b.length),e=a.indexOf("<v:imagedata",c+b.length),-1<d&&-1<e&&e<d)if(f=a.indexOf("/>",e+12),-1<f)e=a.substring(0,c),c=a.substr(c,f-c+2),a=a.substr(d+10),c=DEXTTOP.DEXT5.util.replaceAll(c,"<v:imagedata"," "),c=DEXTTOP.DEXT5.util.replaceAll(c,b,"<v:imagedata "),c=DEXTTOP.DEXT5.util.replaceAll(c,">"," "),c=DEXTTOP.DEXT5.util.rtrim(c),
c+=">",c=DEXTTOP.DEXT5.util.replaceAll(c,"/>"," />"),c=DEXTTOP.DEXT5.util.replaceAll(c,"  "," "),a=e+c+a;else break;else break;else break;return a}
function setPasteClassStyle(a,b,c){for(var d in a){var e=a[d],e=DEXTTOP.DEXT5.util.replaceAll(e,"hairline ","dotted "),e=DEXTTOP.DEXT5.util.replaceAll(e," hairline;"," dotted;"),e=DEXTTOP.DEXT5.util.replaceAll(e,"dot-dot-dash ","dotted "),e=DEXTTOP.DEXT5.util.replaceAll(e," dot-dot-dash;"," dotted;"),e=DEXTTOP.DEXT5.util.replaceAll(e,"dot-dash ","dotted "),e=DEXTTOP.DEXT5.util.replaceAll(e," dot-dash;"," dotted;"),e=DEXTTOP.DEXT5.util.replaceAll(e,"dot-dash-slanted ","dotted "),e=DEXTTOP.DEXT5.util.replaceAll(e,
" dot-dash-slanted;"," dotted;");d=d.split(",")[0];d=d.substring(d.indexOf("."));if("."==d.substring(0,1)){var f=new RegExp("<[^>]*class=(\"|'|)"+d.substr(1)+"(\"|'|) [\\s\\S]*?>","i");b=setStyleToClass(b,f,d,e);f=new RegExp("<[^>]*class=(\"|'|)"+d.substr(1)+"(\"|'|)>","i");b=setStyleToClass(b,f,d,e)}if(c&&(f=d.toLowerCase(),(-1<f.indexOf("h1")||-1<f.indexOf("h2")||-1<f.indexOf("h3")||-1<f.indexOf("h4")||-1<f.indexOf("h5")||-1<f.indexOf("h6")||-1<f.indexOf("em"))&&""!=e&&(f=new RegExp("<"+d+"[^>]*>",
"igm"),f=b.match(f))))for(var g=f.length,h=0;g>h;h++){var l=b.substring(0,b.indexOf(f[h])),k=f[h];b=b.substring(b.indexOf(f[h])+f[h].length);var m=/(style=("|'|))/i,k=1==m.test(k)?k.replace(m,RegExp.$1+e):k.replace(new RegExp("<"+d,"i"),"<"+d+" style='"+e+"'");b=l+k+b}}return b}
function setStyleToClass(a,b,c,d){for(var e;e=b.exec(a);){var f=a.substring(0,e.index),g=e[0].toString();a=a.substr(e.index+e[0].length);e=/style=("|'|)/i;if(1==e.test(g)){var h=RegExp.$1;"'"==h?d=d.replace(/'/gi,'"'):'"'==h&&(d=d.replace(/"/gi,"'"));g=g.replace(e,"style="+h+d+" ");e=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i");g=g.replace(e,"")}else e=new RegExp("class=(\"|'|)"+c.substr(1)+"(\"|'|)","i"),g=g.replace(e,"style='"+d+"'");a=f+g+a}return a}
function GetFontSizeForWordH1ToH7Tag(a){var b="",c=a.indexOf("font-size");-1<c&&(a=a.substr(c),c=a.indexOf(";"),-1<c&&(b=a.substring(0,c),b+=";"));return b}function isHwpPasteAction(a){return-1<a.indexOf(">\x3c!--p.")||-1<a.indexOf('<META NAME="Generator" CONTENT="Hancom HWP')||-1<a.indexOf("\x3c!--[if !supportEmptyParas]--\x3e")?!0:!1}
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.officeClean&&(DEXTTOP.DEXT5.util.officeClean=function(a,b){if(""==a||void 0==a)return"";var c=null,d=[];a=a.replace(/\.0px/g,"px");a=a.replace(/\t/g,"");a=DEXTTOP.DEXT5.util.removeOfficeDummyTag(a,"\x3c!--[if supportFields]>","<![endif]--\x3e");c=RegExp("<o:p></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p>\\s+</o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)></o:p>","gi");a=a.replace(c,"");c=RegExp("<o:p ([^>]+)>\\s+</o:p>",
"gi");a=a.replace(c,"");c=RegExp("<w:sdt[^>]*>","gi");a=a.replace(c,"");c=RegExp("</w:sdt>","gi");a=a.replace(c,"");c=RegExp('<[^>]+(lang=["]?en-us["])[^>]*>',"gi");if(c=a.match(c))for(var d=c.length,e=0;e<d;e++){var f=c[e],g=RegExp('\\slang=[\\"]?en-us[\\"]?',"gi"),f=f.replace(g,"");a=a.replace(c[e],f)}c=RegExp("<[^>]+(mso)[^>]*>","gi");if(c=a.match(c))for(d=c.length,e=0;e<d;e++)f=c[e],"1"==DEXTTOP.G_CURREDITOR._config.removeMsoClass&&(g=RegExp('\\sclass=[\\"]?(mso)\\w+[\\"]?',"gi"),f=f.replace(g,
"")),f=f.replace(/&quot;/gi,"^"),g=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;',"gi"),f=f.replace(g,""),g=RegExp('(\\s+)?mso-number-format:(\\s+)?"(.+?)"(\\s+)?;?',"gi"),f=f.replace(g,""),g=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?'\"\\^@%\\.\\\\_]+; ?","gi"),f=f.replace(g,""),g=RegExp("\\s?mso-[\\w\uac00-\ud7a3\\-: ?]+(['\"])","gi"),f=f.replace(g,"$1"),f=f.replace(/\^/gi,"&quot;"),a=a.replace(c[e],f);a=DEXTTOP.DEXT5.util.replaceAll(a,"hairline","dotted");for(e=0;5>e;e++){d=["o:p","span",
"font"];g=d.length;for(f=0;f<g;f++)c=new RegExp("<"+d[f]+"[^>]*></"+d[f]+">","gi"),a=a.replace(c,""),c=new RegExp("<"+d[f]+"[^>]*>&nbsp;</"+d[f]+">","gi"),a=a.replace(c,"&nbsp;"),"span"!=d[f]&&(c=new RegExp("<"+d[f]+"[^>]*> </"+d[f]+">","gi"),a=a.replace(c,"&nbsp;"));d=["o","v","w","m","x"];g=d.length;for(f=0;f<g;f++)0==f&&(a=a.replace(/<o:p/gi,"<dexto:p")),-1<a.indexOf("<"+d[f])&&(c=new RegExp("<"+d[f]+":[^/>]+/>","gi"),a=a.replace(c,""),c=new RegExp("<"+d[f]+":[^>]+>[^<]*</"+d[f]+":[^>]+>","gi"),
a=a.replace(c,""),"v"==d[f]&&(c=new RegExp("<"+d[f]+":[^>]+>","gi"),a=a.replace(c,""),c=new RegExp("</"+d[f]+":[^>]+>","gi"),a=a.replace(c,""))),f==g-1&&(a=a.replace(/<dexto:p/gi,"<o:p"))}a=a.replace(/style=""/gi,"");a=a.replace(/style=''/gi,"");a=a.replace(/\s>/gi,">");a=DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp(a);a=a.replace(/<\/td>&nbsp;<\/tr>/g,"</td></tr>");a=a.replace(/<\/td>&nbsp;<\/td>/g,"</td></td>");a=a.replace(/<\/th>&nbsp;<\/tr>/g,"</th></tr>");a=a.replace(/<\/th>&nbsp;<\/th>/g,"</th></th>");
if(DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){var c=a.length,f=d=!1,h=g="",l="";if(-1==a.indexOf("<")&&-1==a.indexOf(">"))for(e=0;e<c;e++)g=a.charAt(e),h=a.charAt(e+1)," "!=g&&32!=g.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(g="&nbsp;"),l+=g;else for(e=0;e<c;e++)g=a.charAt(e),h=a.charAt(e+1),"<"==g?(d=!1,f="p"==h.toLowerCase()?!0:!1):">"==g&&1==f?d=!0:1!=d||" "!=g&&32!=g.charCodeAt(0)||" "!=h&&32!=h.charCodeAt(0)||(g="&nbsp;"),l+=g;a=l}0==b&&(a=DEXTTOP.DEXT5.util.removeLocalFileImage(a));
return a});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.removeLocalFileImage&&(DEXTTOP.DEXT5.util.removeLocalFileImage=function(a){return""==a||void 0==a?"":a=a.replace(RegExp("<img[^>]+file:///[^>]+>","gi"),"")});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.removeOfficeDummyTag&&(DEXTTOP.DEXT5.util.removeOfficeDummyTag=function(a,b,c){var d=a;try{for(var e=a.indexOf(b),f=a.indexOf(c);-1<e&&-1<f;)var g=d.substring(0,e),h=d.substring(f+c.length),d=g+h,e=d.indexOf(b),f=d.indexOf(c)}catch(l){d=a}return d});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.replaceAll&&(DEXTTOP.DEXT5.util.replaceAll=function(a,b,c){a&&""!=a&&(a=a.split(b).join(c));return a});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp&&(DEXTTOP.DEXT5.util.replaceOneSpaceToNbsp=function(a){var b=a,c,d="";try{for(var e="span font a b strong i em strike u sup sub".split(" "),f=e.length,g=0;g<f;g++){var h=!0,l=e[g];("font"==l||"b"==l||"em"==l||"sup"==l||"sub"==l)&&0>b.toLowerCase().indexOf("<"+l)&&(h=!1);if(h)for(var k=0;k<f;k++){d=b;c=new RegExp("<"+e[g]+" *([^>?+])*>(\\s+)</"+e[k]+">","gi");reg_exp2="u"==e[k]?new RegExp("</"+e[g]+">(\\s+)<"+
e[k]+"[^l]","gi"):new RegExp("</"+e[g]+">(\\s+)<"+e[k]+" *([^>?+])*>","gi");reg_exp3=new RegExp("<"+e[g]+" *([^>?+])*>(\\s+)<"+e[k]+">","gi");reg_exp4="u"==e[k]?new RegExp("</"+e[g]+">(\\s+)</"+e[k]+"[^l]","gi"):new RegExp("</"+e[g]+">(\\s+)</"+e[k]+" *([^>?+])*>","gi");try{var m=b.match(c);if(m)for(var t=m.length,p=0;p<t;p++){var n=m[p];if(!("b"==e[g]&&-1<n.toLowerCase().indexOf("<br")))var q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n)}if(m=
b.match(reg_exp2))for(t=m.length,p=0;p<t;p++)n=m[p],"b"==e[k]&&-1<n.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n));if(m=b.match(reg_exp3))for(t=m.length,p=0;p<t;p++)n=m[p],"b"==e[g]&&-1<n.toLowerCase().indexOf("<br")||(q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s","gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n));if(m=b.match(reg_exp4))for(t=m.length,p=0;p<t;p++)n=m[p],q=/>\s+</.exec(n),r=q[0].replace(RegExp("\\s\\s",
"gi"),"&nbsp;&nbsp;"),n=n.replace(q,r),b=b.replace(m[p],n)}catch(u){b=d}}}for(g=0;g<f;g++)if(h=!0,l=e[g],("font"==l||"b"==l||"em"==l||"sup"==l||"sub"==l)&&0>d.toLowerCase().indexOf("<"+l)&&(h=!1),h){"b"==l?(b=b.replace(/<br/gi,"<temp_br"),b=b.replace(/<\/br/gi,"</temp_br")):"u"==l&&(b=b.replace(/<ul/gi,"<temp_ul"),b=b.replace(/<\/ul/gi,"</temp_ul"));for(k=0;k<f;k++)c=new RegExp("/"+e[g]+">\\s<"+e[k],"gi"),b=b.replace(c,"/"+e[g]+">&nbsp;<"+e[k]),c=new RegExp("/"+e[g]+">\\s\\n<"+e[k],"gi"),b=b.replace(c,
"/"+e[g]+">&nbsp;<"+e[k]);"b"==l?(b=b.replace(/<temp_br/gi,"<br"),b=b.replace(/<\/temp_br/gi,"</br")):"u"==l&&(b=b.replace(/<temp_ul/gi,"<ul"),b=b.replace(/<\/temp_ul/gi,"</ul"))}}catch(v){b=a}return b});"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.rtrim&&(DEXTTOP.DEXT5.util.rtrim=function(a){return""==a?a:a.replace(/\s+$/,"")});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.hexToBytes&&(DEXTTOP.DEXT5.util.hexToBytes=function(a){for(var b=[],c=a.length/2,d=0,d=0;d<c;d++)b.push(parseInt(a.substr(2*d,2),16));return b});
"undefined"!=typeof DEXTTOP.DEXT5&&"undefined"==typeof DEXTTOP.DEXT5.util.bytesToBase64&&(DEXTTOP.DEXT5.util.bytesToBase64=function(a){for(var b="",c=a.length,d=0;d<c;d+=3){var e=a.slice(d,d+3),f=e.length,g=[],h=void 0;if(3>f)for(h=f;3>h;h++)e[h]=0;g[0]=(252&e[0])>>2;g[1]=(3&e[0])<<4|e[1]>>4;g[2]=(15&e[1])<<2|(192&e[2])>>6;g[3]=63&e[2];for(h=0;4>h;h++)b+=h<=f?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(g[h]):"="}return b});
